[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newer"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Toshihiro Kamiya", email = "kamiya@mbj.nifty.com" },
]
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
]
urls = {Homepage = "https://github.com/tos-kamiya/newer"}
dependencies = [
  "python-magic",
]

[tool.hatch.version]
path = "src/newer/__about__.py"

[project.scripts]
newer = "newer:main"
